# Generated by Django 2.0.2 on 2018-09-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='author',
            new_name='posted_by',
        ),
    ]
